services:
  mysql:
    image: mysql:8.4
    container_name: feel-mysql
    mem_limit: 250m
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: feelarchive
    command:
      - --innodb_buffer_pool_size=128M
      - --performance_schema=OFF
      - --table_open_cache=64
      - --thread_cache_size=4
      - --max_connections=30
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --binlog_expire_logs_seconds=86400
      - --max_binlog_size=100M
    networks:
      - feel-archive-net

  redis:
    image: redis:latest
    container_name: feel-redis
    mem_limit: 50m
    restart: always
    ports:
      - "16379:6379"
    networks:
      - feel-archive-net

  prometheus:
    image: prom/prometheus:latest
    container_name: feel-prometheus
    restart: always
    mem_limit: 50m
    ports:
      - "9090:9090"
    command:
      - --storage.tsdb.retention.time=3d
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./prometheus.prod.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    networks:
      - feel-archive-net

networks:
  feel-archive-net:
    name: feel-archive-net
