services:
  mysql:
    image: mysql:8.4
    container_name: feel-mysql
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image : redis:latest
    container_name: feel-redis
    restart: always
    ports:
      - "16379:6379"
